name: Java CD Release

on:
  workflow_run:
    workflows: ["Java CI with Maven"] # Chạy CD sau khi CI (tích xanh) thành công
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (Package)
      # Lệnh này sẽ tạo ra file .war hoặc .jar trong thư mục target
      run: mvn clean package -DskipTests

    - name: Upload Build Artifact
      # Lưu lại sản phẩm để bạn có thể tải về từ GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ASM4-Package
        path: target/*.war # Hoặc *.jar tùy cấu hình pom.xml của bạn